# Generated by Django 4.2.2 on 2024-01-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wycieczka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("dataRozpoczecia", models.DateField()),
                ("dataZakonczenia", models.DateField()),
                ("maxIloscMiejsc", models.IntegerField()),
                ("iloscZajetychMiejsc", models.IntegerField()),
                ("cena", models.IntegerField()),
                ("zdjecie", models.CharField(max_length=255)),
                ("opis", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ocena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wartosc", models.IntegerField()),
                (
                    "wycieczka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.wycieczka"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KupionaWycieczka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("ilosc", models.IntegerField()),
                ("dataKupienia", models.DateField()),
                (
                    "wycieczka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.wycieczka"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Komentarz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("tekst", models.CharField(max_length=500)),
                (
                    "wycieczka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.wycieczka"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KaruzelaZdjec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zdjecie", models.CharField(max_length=255)),
                (
                    "wycieczka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.wycieczka"
                    ),
                ),
            ],
        ),
    ]
