# Generated by Django 4.2.2 on 2024-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="karuzelazdjec",
            name="wycieczka",
        ),
        migrations.RemoveField(
            model_name="komentarz",
            name="wycieczka",
        ),
        migrations.RemoveField(
            model_name="ocena",
            name="wycieczka",
        ),
        migrations.AddField(
            model_name="wycieczka",
            name="karulaZdjec",
            field=models.ManyToManyField(to="api.karuzelazdjec"),
        ),
        migrations.AddField(
            model_name="wycieczka",
            name="komentarze",
            field=models.ManyToManyField(to="api.komentarz"),
        ),
        migrations.AddField(
            model_name="wycieczka",
            name="oceny",
            field=models.ManyToManyField(to="api.ocena"),
        ),
    ]
