# Generated by Django 4.2.2 on 2024-01-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_karuzelazdjec_wycieczka_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="komentarz",
            old_name="username",
            new_name="email",
        ),
    ]
