# Generated by Django 4.2.2 on 2024-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_karulazdjec_wycieczka_karuzelazdjec"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.CharField(default="user", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wycieczka",
            name="karuzelaZdjec",
            field=models.ManyToManyField(blank=True, to="api.karuzelazdjec"),
        ),
        migrations.AlterField(
            model_name="wycieczka",
            name="komentarze",
            field=models.ManyToManyField(blank=True, to="api.komentarz"),
        ),
        migrations.AlterField(
            model_name="wycieczka",
            name="oceny",
            field=models.ManyToManyField(blank=True, to="api.ocena"),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
