# Generated by Django 4.2.2 on 2024-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_group_alter_wycieczka_karuzelazdjec_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wycieczka",
            name="oceny",
        ),
        migrations.AddField(
            model_name="wycieczka",
            name="iloscOcen",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wycieczka",
            name="sredniaOcena",
            field=models.FloatField(null=True),
        ),
    ]
