# Generated by Django 4.2.2 on 2024-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_wycieczka_oceny_wycieczka_iloscocen_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ocena",
        ),
        migrations.AddField(
            model_name="komentarz",
            name="data",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="komentarz",
            name="ocena",
            field=models.IntegerField(null=True),
        ),
    ]
