# Generated by Django 4.2.2 on 2024-01-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_delete_ocena_komentarz_data_komentarz_ocena"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("wartosc", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="komentarz",
            name="ocena",
        ),
        migrations.AddField(
            model_name="komentarz",
            name="nazwa",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
