# Generated by Django 4.2.2 on 2024-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_ocena_remove_komentarz_ocena_komentarz_nazwa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wycieczka",
            name="iloscOcen",
        ),
        migrations.RemoveField(
            model_name="wycieczka",
            name="sredniaOcena",
        ),
        migrations.AddField(
            model_name="wycieczka",
            name="oceny",
            field=models.ManyToManyField(null=True, to="api.ocena"),
        ),
    ]
