# Generated by Django 5.0 on 2024-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_wycieczka_iloscocen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wycieczka",
            name="kraj",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
