# Generated by Django 4.2.2 on 2024-01-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_wycieczka_kraj"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
