# Generated by Django 4.2.2 on 2024-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_storedtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionPersistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessionType", models.CharField(max_length=255)),
            ],
        ),
    ]
